### ISSUE TITLE
Перейти на хранение индексов вместо указателей в memory manager

### ISSUE THREAD

**Issue by ghost** [Konard/LinksPlatform#1]
Отказываемся от ссылок, переходим на индексы.

**Comment by Konard** [comment]
Продолжаю переход на индексы. Тестирование пока ещё невозможно.

**Comment by Konard** [comment]
Тестирование PersistentMemoryManager.c под Windows прошло успешно.
https://www.youtube.com/watch?v=A-9eegP9cSM

**Comment by Konard** [comment]
https://www.youtube.com/watch?v=lNR68vigYbE
https://www.youtube.com/watch?v=bYLAtYDTfPc
https://github.com/Konard/LinksPlatform/commit/eddfec45199a67926952d6e64bf3e3eb608ed631
