### ISSUE TITLE
Range

### ISSUE THREAD

**Issue by Konard** [Konard/LinksPlatform#208]

**Comment by konard** [comment]
I'm working on this optimization issue. Could you please provide more details about what "ranges list" approach means in this context?

From what I see in the old code at `28.03.2010-04.11.2010/Net/Net/Link.cs`, the current implementation uses linked lists to manage Link references via fields like:
- `m_FirstRefererBySource` / `m_NextSiblingRefererBySource`
- `m_FirstRefererByLinker` / `m_NextSiblingRefererByLinker`
- `m_FirstRefererByTarget` / `m_NextSiblingRefererByTarget`

What would the "ranges list" approach look like? Some possibilities:
1. Using an array/list to store ranges of Link indices (e.g., `List<(int start, int end)>`)?
2. Using a memory allocator with range tracking for Link objects?
3. Something else?

Understanding this will help me implement the optimal solution. Thanks!
