### ISSUE TITLE
Update WebTerminal to support .NET Core RTM

### ISSUE THREAD

**Issue by Konard** [Konard/LinksPlatform#217]

**Comment by Antttttttt** [comment]
а скоро будет веб терминал?

**Comment by Konard** [comment]
Если ждать - долго, если помогать - быстрее.

**Comment by Antttttttt** [comment]
Можно и так))))

2016-09-20 11:27 GMT+03:00 Konstantin Dyachenko <notifications@github.com>:

**Comment by Antttttttt** [comment]
Помогать!

2016-09-20 13:28 GMT+03:00 Антон Зверев <anton.zverev7772021@gmail.com>:

**Comment by Konard** [comment]
Ну рекомендую посмотреть сюда - https://github.com/Konard/LinksPlatform/projects/3
А так же попробовать запустить текущую реализацию WebTerminal, она сейчас поддерживает визуализацию тройных связей. Но в основном в разработке используются двойные связи, поэтому перевод этого проекта с ASP.NET на ASP.NET Core позволит поддержать сразу две реализации.

**Comment by Konard** [comment]
Текущая реализация тройных связей на си - https://github.com/Konard/LinksPlatform/tree/master/Platform/Platform.Data.Kernel

**Comment by Konard** [comment]
Текущая реализация консольного терминала - https://github.com/Konard/LinksPlatform/tree/master/Platform/Platform.Data.ConsoleTerminal
В данный момент консольный терминал позволяет искать и создавать текстовые последовательности. Связи же используются только как пары символов или пары последовательностей. Т.е. по сути ConsoleTerminal следовало бы назвать ConsoleSequencesTerminal или ConsoleStringsTerminal, но можно продумать возможность взаимодействия на нескольких уровнях (на уровне связей, последовательностей вообще (связей неограниченной мерности или по количеству компонентов), и последовательностей текстовых (на основе символов юникода) - строк). Текущий WebTerminal это всего лишь две визуализации структуры из связей (через древовидное представление). По факту хорошо бы поддержать не только отображение (операцию чтения), но так же и операции записи (создание, обновление, удаление, либо одну унифицированную операцию замещения). И сделать так, чтобы общий для консольного и веб-терминала функционал был выделен в виде отдельного объекта/класса. Некоторые визуализации в будущем возможно было бы перенести и консольный терминал, чтобы трансформировать хранилище связей можно было и без полноценного графического интерфейса.

**Comment by Konard** [comment]
Если есть возможность помочь - рекомендую сделать форк и начать эксперименты, а если вдруг нужна будет помощь - обращаться ко мне, желательно через [vk.com/konard](https://vk.com/konard).

**Comment by Antttttttt** [comment]
а какие алгоритмы Ты выбрал для операции замещения?


2016-09-20 16:32 GMT+03:00 Konstantin Dyachenko <notifications@github.com>:

**Comment by Konard** [comment]
Операция замещения это по сути расширенная операция обновления. Которая за счёт того, что допускает дополнительное значение "пустота" в качестве аргумента начинает вмещать в себя все 3 операции (Создание, Обновление и Удаление).
Пример:
(nothing) => (2: 2 2) // создание связи
(2: 2 2) => (2: 4 3) // обновление связи
(2: 4 3) => (nothing) // удаление связи
По сути (nothing) можно заменить на (0: 0 0), если есть соглашение что связь с адресом 0 существовать не может, и обозначает отсутствие связи или саму пустоту.
Оказалось кстати, что и машина тьюринга и алгорифмы маркова вводят дополнительное понятие пустого символа. Поэтому почему бы его не использовать на полную, и не усложнять разными операциями, которые в таком случае являются частным случаем одной операции.
