### ISSUE TITLE
Atomicity

### ISSUE THREAD

**Issue by Konard** [Konard/LinksPlatform#40]
Implement transitions groups (transactions). Each transaction should be atomic ("all or none" transitions commited).

**Comment by rupole1185** [comment]
Hi Konard! I am Ruggero from CONSELF. I would like to talk with you if possible! Please contact me at the following address: ruggero.poletto@conself.com

thanks!

**Comment by Konard** [comment]
https://github.com/Konard/LinksPlatform/commit/e4a9a1db18fcde46e690f44b4359278a4e204590 (added initial support for single transaction atomicity)
