### ISSUE TITLE
Remove Links from Namespaces, as it conflicts with Links classes

### ISSUE THREAD

**Issue by Konard** [Konard/LinksPlatform#41]

**Comment by rupole1185** [comment]
Hi Konard! I am Ruggero from CONSELF. I would like to talk with you if possible! Please contact me at the following address: ruggero.poletto@conself.com

thanks!

**Comment by Konard** [comment]
https://github.com/Konard/LinksPlatform/commit/39c39b0638de6099f83175afe8ae0d3990788fff done
