### ISSUE TITLE
Implement stable algorithm for optimal subsequence groupings (minification of total sequences size) aka Compression

### ISSUE THREAD

**Issue by Konard** [Konard/LinksPlatform#9]

**Comment by werkzeuge** [comment]
Алгоритм LZW подойдёт?

**Comment by Konard** [comment]
Вопрос не в том, чтобы буквально сжать данные, это и так можно сделать с файлом бд. Вопрос в том, чтобы в процессе работы БД те части последовательностей (подпоследовательности), если обнаружен повтор выделялись в отдельную последовательность. Тогда каждая уникальная часть последовательности будет существовать ровно один раз, тем самым будет экономиться место для хранения связей, а также база данных получит дополнительную структуризацию данных автоматически за счёт выполнения такого алгоритма.

**Comment by werkzeuge** [comment]
То есть, UNIQUE KEY.

**Comment by Konard** [comment]
https://en.wikipedia.org/wiki/Huffman_coding

**Comment by Konard** [comment]
https://en.wikipedia.org/wiki/Byte_pair_encoding - looks like the most promising version of algorithm.

**Comment by Konard** [comment]
https://github.com/Konard/LinksPlatform/commit/c7a08e692839891fbe90ea60af3e3dd666a1dcee done

**Comment by werkzeuge** [comment]
Почему закрыл issue? Научился сжимать UTF-16?

**Comment by Konard** [comment]
Любых последовательностей, UTF-16 это лишь пример.

**Comment by Konard** [comment]
Possible optimizations of compression:
- [ ] Update multiple pairs at a time of replacement.
- [ ] Global dictionary / count of pairs across multiple compressions
- [ ] Relative frequency in % (possible with total characters weight of that average frequency)
